# Generated by Django 5.1.5 on 2025-06-06 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SERVIDO', 'Servido'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creado'],
            },
        ),
        migrations.CreateModel(
            name='Comensal',
            fields=[
                ('comensal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comensales', to='pedidos.orden')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.CharField(blank=True, help_text='Extras separados por comas', max_length=100)),
                ('comensales', models.ManyToManyField(related_name='productos_pedidos', to='pedidos.comensal')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedidos.orden')),
            ],
        ),
    ]
