# Generated by Django 5.1.5 on 2025-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='pan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tostada',
            name='pan',
            field=models.BooleanField(default=True),
        ),
    ]
