# Generated by Django 5.1.5 on 2025-06-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_comida_pan_alter_tostada_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tostada',
            name='tipo_tostada',
        ),
    ]
