# Generated by Django 5.1.5 on 2025-06-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_bebida_stock_combo_stock_comida_stock_helado_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='helado',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='pan',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tostada',
            name='stock',
        ),
    ]
