# Generated by Django 5.1.5 on 2025-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_combo_stock_remove_comida_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pan',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
